/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContactLazyTestImport } from './routes/contact.lazy.test'

// Create Virtual Routes

const PastLazyImport = createFileRoute('/past')()
const OrderLazyImport = createFileRoute('/order')()
const ContactLazyImport = createFileRoute('/contact')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PastLazyRoute = PastLazyImport.update({
  path: '/past',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/past.lazy').then((d) => d.Route))

const OrderLazyRoute = OrderLazyImport.update({
  path: '/order',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/order.lazy').then((d) => d.Route))

const ContactLazyRoute = ContactLazyImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ContactLazyTestRoute = ContactLazyTestImport.update({
  path: '/lazy/test',
  getParentRoute: () => ContactLazyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyImport
      parentRoute: typeof rootRoute
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderLazyImport
      parentRoute: typeof rootRoute
    }
    '/past': {
      id: '/past'
      path: '/past'
      fullPath: '/past'
      preLoaderRoute: typeof PastLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact/lazy/test': {
      id: '/contact/lazy/test'
      path: '/lazy/test'
      fullPath: '/contact/lazy/test'
      preLoaderRoute: typeof ContactLazyTestImport
      parentRoute: typeof ContactLazyImport
    }
  }
}

// Create and export the route tree

interface ContactLazyRouteChildren {
  ContactLazyTestRoute: typeof ContactLazyTestRoute
}

const ContactLazyRouteChildren: ContactLazyRouteChildren = {
  ContactLazyTestRoute: ContactLazyTestRoute,
}

const ContactLazyRouteWithChildren = ContactLazyRoute._addFileChildren(
  ContactLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRouteWithChildren
  '/order': typeof OrderLazyRoute
  '/past': typeof PastLazyRoute
  '/contact/lazy/test': typeof ContactLazyTestRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRouteWithChildren
  '/order': typeof OrderLazyRoute
  '/past': typeof PastLazyRoute
  '/contact/lazy/test': typeof ContactLazyTestRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRouteWithChildren
  '/order': typeof OrderLazyRoute
  '/past': typeof PastLazyRoute
  '/contact/lazy/test': typeof ContactLazyTestRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/order' | '/past' | '/contact/lazy/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/order' | '/past' | '/contact/lazy/test'
  id: '__root__' | '/' | '/contact' | '/order' | '/past' | '/contact/lazy/test'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ContactLazyRoute: typeof ContactLazyRouteWithChildren
  OrderLazyRoute: typeof OrderLazyRoute
  PastLazyRoute: typeof PastLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ContactLazyRoute: ContactLazyRouteWithChildren,
  OrderLazyRoute: OrderLazyRoute,
  PastLazyRoute: PastLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/contact",
        "/order",
        "/past"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/contact": {
      "filePath": "contact.lazy.jsx",
      "children": [
        "/contact/lazy/test"
      ]
    },
    "/order": {
      "filePath": "order.lazy.jsx"
    },
    "/past": {
      "filePath": "past.lazy.jsx"
    },
    "/contact/lazy/test": {
      "filePath": "contact.lazy.test.jsx",
      "parent": "/contact"
    }
  }
}
ROUTE_MANIFEST_END */
